import OpenAI from "openai";
import pdf from "pdf-parse/lib/pdf-parse.js";

const chatgpt = new OpenAI({ apiKey: process.env.API_KEY });
const vectorFile = `${process.env.FILE_ID_1}`;
const vectorFile2 = `${process.env.FILE_ID_2}`;

export const reviewResume = async (req, res, next) => {
  try {
    const file = req.file;

    if (!file) {
      const error = new Error("Problem with resume");
      error.status = 400;
      next(error);
    }

    if (file.mimetype !== "application/pdf") {
      const error = new Error("Only PDF files are allowed");
      error.status = 400;
      next(error);
    }

    const pdfBuffer = file.buffer;
    const pdfData = await pdf(pdfBuffer);
    const resumeText = pdfData.text;

    const response = await chatgpt.responses.create({
      model: "gpt-4.1",
      tools: [
        {
          type: "file_search",
          vector_store_ids: [vectorFile, vectorFile2],
        },
      ],
      input: `You are a career advisor for students applying to their first internships. Review resumes using the attached guides and give clear, structured feedback. If the content below does not seem like a resume, do not give any feedback. Simply respond, word for word, "This is not a resume, or your resume needs some serious work". If the content below does seem like a resume do give feedback. Do not use any subjective words. Remain professional. It is imperative and important that you be as strict as possible when following these guidelines. If the resume guides include resume templates, please only consider the resume templates intended for engineering students, and not any other resume template. If the resume guides include advice for other industries, please only consider the advice intended for engineering. The feedback returned should start with something along these lines. "After reviewing your resume following engineering resume guides, here is your feedback". Do not offer to review again, this interaction with the user will be one-way. Do not mention a single word about future experience. If it seems like the experience listed on the resume will take place in the future, pretend like it will not and review other things about the experience. Do not say anything like "clarify that this position is in the future" or "this position seems to take place in the future and does not align with your education timeline". Do not use any bolded text. Do not use a point system. Be sure to include a summary of feedback and some actionable steps at the end. Please make absolutely sure that for the closing statement, say the following word for word: "This feedback was generated by OpenAI ChatGPT-4.1. Please take this feedback with a grain of salt since it was generated by ChatGPT.". Remember to be less strict on the formatting and hyperlinks since it could be a matter of conversion between pdf and raw text. Here is the resume: ${resumeText}`,
    });

    res.json(response);
  } catch (error) {
    next(error);
  }
};
